"""initial schema

Revision ID: 267a2d5d2f22
Revises: 
Create Date: 2026-07-23 03:42:57.445801
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '267a2d5d2f22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('timeframe_minutes', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('default_invest_ratio', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_code'), 'strategy', ['code'], unique=True)
    op.create_index(op.f('ix_strategy_id'), 'strategy', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('bot_enabled', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=16), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('telegram_link_code', sa.String(length=16), nullable=True),
    sa.Column('telegram_link_expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_telegram_link_code'), 'user', ['telegram_link_code'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_key', sa.String(length=512), nullable=True),
    sa.Column('encrypted_secret_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=False)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=True)
    op.create_table('paper_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('net_deposit', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_account_user_id'), 'paper_account', ['user_id'], unique=True)
    op.create_table('position_mismatch_incident',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('mismatch_type', sa.String(length=32), nullable=False),
    sa.Column('actual_total', sa.Float(), nullable=False),
    sa.Column('strategy_volume', sa.Float(), nullable=False),
    sa.Column('difference', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('notified_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_mismatch_incident_currency'), 'position_mismatch_incident', ['currency'], unique=False)
    op.create_index(op.f('ix_position_mismatch_incident_id'), 'position_mismatch_incident', ['id'], unique=False)
    op.create_index(op.f('ix_position_mismatch_incident_mismatch_type'), 'position_mismatch_incident', ['mismatch_type'], unique=False)
    op.create_index(op.f('ix_position_mismatch_incident_resolved_at'), 'position_mismatch_incident', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_position_mismatch_incident_user_id'), 'position_mismatch_incident', ['user_id'], unique=False)
    op.create_table('strategy_runtime',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('timeframe_minutes', sa.Integer(), nullable=False),
    sa.Column('candle_open_time', sa.DateTime(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'timeframe_minutes', name='uq_strategy_runtime_strategy_timeframe')
    )
    op.create_index(op.f('ix_strategy_runtime_id'), 'strategy_runtime', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_runtime_strategy_id'), 'strategy_runtime', ['strategy_id'], unique=False)
    op.create_table('strategy_signal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('timeframe_minutes', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('candle_open_time', sa.DateTime(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'timeframe_minutes', 'candle_open_time', 'action', name='uq_strategy_signal_candle_action')
    )
    op.create_index(op.f('ix_strategy_signal_id'), 'strategy_signal', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_signal_market'), 'strategy_signal', ['market'], unique=False)
    op.create_index(op.f('ix_strategy_signal_strategy_id'), 'strategy_signal', ['strategy_id'], unique=False)
    op.create_table('user_strategy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('invest_ratio', sa.Float(), nullable=False),
    sa.Column('stop_loss_rate', sa.Float(), nullable=True),
    sa.Column('take_profit_rate', sa.Float(), nullable=True),
    sa.Column('timeframe_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategy.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'strategy_id', 'mode', name='uq_user_strategy_mode')
    )
    op.create_index(op.f('ix_user_strategy_id'), 'user_strategy', ['id'], unique=False)
    op.create_index(op.f('ix_user_strategy_mode'), 'user_strategy', ['mode'], unique=False)
    op.create_index(op.f('ix_user_strategy_strategy_id'), 'user_strategy', ['strategy_id'], unique=False)
    op.create_index(op.f('ix_user_strategy_user_id'), 'user_strategy', ['user_id'], unique=False)
    op.create_table('strategy_execution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=False),
    sa.Column('user_strategy_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('order_amount', sa.Float(), nullable=True),
    sa.Column('order_volume', sa.Float(), nullable=True),
    sa.Column('order_uuid', sa.String(length=64), nullable=True),
    sa.Column('executed_volume', sa.Float(), nullable=True),
    sa.Column('average_price', sa.Float(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('notification_sent', sa.Boolean(), nullable=False),
    sa.Column('settlement_notification_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['strategy_signal.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_strategy_id'], ['user_strategy.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id', 'user_strategy_id', name='uq_signal_user_strategy_execution')
    )
    op.create_index(op.f('ix_strategy_execution_id'), 'strategy_execution', ['id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_mode'), 'strategy_execution', ['mode'], unique=False)
    op.create_index(op.f('ix_strategy_execution_order_uuid'), 'strategy_execution', ['order_uuid'], unique=False)
    op.create_index(op.f('ix_strategy_execution_signal_id'), 'strategy_execution', ['signal_id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_user_id'), 'strategy_execution', ['user_id'], unique=False)
    op.create_index(op.f('ix_strategy_execution_user_strategy_id'), 'strategy_execution', ['user_strategy_id'], unique=False)
    op.create_table('paper_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('strategy_execution_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_account.id'], ),
    sa.ForeignKeyConstraint(['strategy_execution_id'], ['strategy_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_ledger_account_id'), 'paper_ledger', ['account_id'], unique=False)
    op.create_index(op.f('ix_paper_ledger_created_at'), 'paper_ledger', ['created_at'], unique=False)
    op.create_index(op.f('ix_paper_ledger_strategy_execution_id'), 'paper_ledger', ['strategy_execution_id'], unique=False)
    op.create_table('position_sync_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_strategy_id', sa.Integer(), nullable=False),
    sa.Column('strategy_execution_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=16), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('reference_price', sa.Float(), nullable=False),
    sa.Column('difference_before', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_execution_id'], ['strategy_execution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_strategy_id'], ['user_strategy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_sync_adjustment_created_at'), 'position_sync_adjustment', ['created_at'], unique=False)
    op.create_index(op.f('ix_position_sync_adjustment_currency'), 'position_sync_adjustment', ['currency'], unique=False)
    op.create_index(op.f('ix_position_sync_adjustment_id'), 'position_sync_adjustment', ['id'], unique=False)
    op.create_index(op.f('ix_position_sync_adjustment_strategy_execution_id'), 'position_sync_adjustment', ['strategy_execution_id'], unique=True)
    op.create_index(op.f('ix_position_sync_adjustment_user_id'), 'position_sync_adjustment', ['user_id'], unique=False)
    op.create_index(op.f('ix_position_sync_adjustment_user_strategy_id'), 'position_sync_adjustment', ['user_strategy_id'], unique=False)
    op.create_table('trade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('strategy_execution_id', sa.Integer(), nullable=True),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['strategy_execution_id'], ['strategy_execution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trade_created_at'), 'trade', ['created_at'], unique=False)
    op.create_index(op.f('ix_trade_id'), 'trade', ['id'], unique=False)
    op.create_index(op.f('ix_trade_strategy_execution_id'), 'trade', ['strategy_execution_id'], unique=True)
    op.create_index(op.f('ix_trade_user_id'), 'trade', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trade_user_id'), table_name='trade')
    op.drop_index(op.f('ix_trade_strategy_execution_id'), table_name='trade')
    op.drop_index(op.f('ix_trade_id'), table_name='trade')
    op.drop_index(op.f('ix_trade_created_at'), table_name='trade')
    op.drop_table('trade')
    op.drop_index(op.f('ix_position_sync_adjustment_user_strategy_id'), table_name='position_sync_adjustment')
    op.drop_index(op.f('ix_position_sync_adjustment_user_id'), table_name='position_sync_adjustment')
    op.drop_index(op.f('ix_position_sync_adjustment_strategy_execution_id'), table_name='position_sync_adjustment')
    op.drop_index(op.f('ix_position_sync_adjustment_id'), table_name='position_sync_adjustment')
    op.drop_index(op.f('ix_position_sync_adjustment_currency'), table_name='position_sync_adjustment')
    op.drop_index(op.f('ix_position_sync_adjustment_created_at'), table_name='position_sync_adjustment')
    op.drop_table('position_sync_adjustment')
    op.drop_index(op.f('ix_paper_ledger_strategy_execution_id'), table_name='paper_ledger')
    op.drop_index(op.f('ix_paper_ledger_created_at'), table_name='paper_ledger')
    op.drop_index(op.f('ix_paper_ledger_account_id'), table_name='paper_ledger')
    op.drop_table('paper_ledger')
    op.drop_index(op.f('ix_strategy_execution_user_strategy_id'), table_name='strategy_execution')
    op.drop_index(op.f('ix_strategy_execution_user_id'), table_name='strategy_execution')
    op.drop_index(op.f('ix_strategy_execution_signal_id'), table_name='strategy_execution')
    op.drop_index(op.f('ix_strategy_execution_order_uuid'), table_name='strategy_execution')
    op.drop_index(op.f('ix_strategy_execution_mode'), table_name='strategy_execution')
    op.drop_index(op.f('ix_strategy_execution_id'), table_name='strategy_execution')
    op.drop_table('strategy_execution')
    op.drop_index(op.f('ix_user_strategy_user_id'), table_name='user_strategy')
    op.drop_index(op.f('ix_user_strategy_strategy_id'), table_name='user_strategy')
    op.drop_index(op.f('ix_user_strategy_mode'), table_name='user_strategy')
    op.drop_index(op.f('ix_user_strategy_id'), table_name='user_strategy')
    op.drop_table('user_strategy')
    op.drop_index(op.f('ix_strategy_signal_strategy_id'), table_name='strategy_signal')
    op.drop_index(op.f('ix_strategy_signal_market'), table_name='strategy_signal')
    op.drop_index(op.f('ix_strategy_signal_id'), table_name='strategy_signal')
    op.drop_table('strategy_signal')
    op.drop_index(op.f('ix_strategy_runtime_strategy_id'), table_name='strategy_runtime')
    op.drop_index(op.f('ix_strategy_runtime_id'), table_name='strategy_runtime')
    op.drop_table('strategy_runtime')
    op.drop_index(op.f('ix_position_mismatch_incident_user_id'), table_name='position_mismatch_incident')
    op.drop_index(op.f('ix_position_mismatch_incident_resolved_at'), table_name='position_mismatch_incident')
    op.drop_index(op.f('ix_position_mismatch_incident_mismatch_type'), table_name='position_mismatch_incident')
    op.drop_index(op.f('ix_position_mismatch_incident_id'), table_name='position_mismatch_incident')
    op.drop_index(op.f('ix_position_mismatch_incident_currency'), table_name='position_mismatch_incident')
    op.drop_table('position_mismatch_incident')
    op.drop_index(op.f('ix_paper_account_user_id'), table_name='paper_account')
    op.drop_table('paper_account')
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_telegram_link_code'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_strategy_id'), table_name='strategy')
    op.drop_index(op.f('ix_strategy_code'), table_name='strategy')
    op.drop_table('strategy')
    # ### end Alembic commands ###
