"""add_unique_constraint_to_telegram_chat_id

Revision ID: bad304ee5eec
Revises: 1c7e4a9b2d30
Create Date: 2026-07-27 02:10:07.384547
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bad304ee5eec'
down_revision: Union[str, None] = '1c7e4a9b2d30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['telegram_chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
