"""add_live_trading_enabled_to_user

Revision ID: d66b5ff3b99a
Revises: 101e99953392
Create Date: 2026-07-27 06:40:50.481566
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd66b5ff3b99a'
down_revision: Union[str, None] = '101e99953392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('live_trading_enabled', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'live_trading_enabled')
    # ### end Alembic commands ###
